# © 2020 Comunitea
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
{
    "name": "Custom Lupeon",
    "version": "12.0.1.0.0",
    "category": "connector",
    "author": "Comunitea",
    "maintainer": "Comunitea",
    "website": "www.comunitea.com",
    "license": "AGPL-3",
    "depends": ["product", "sale", "sale_stock", "delivery", "account_payment", 
                "sale_margin", "sale_order_margin_percent", "stock_barcode",
                "stock", "account", "custom_prestashop", "l10n_es_facturae",
                "cost_sheet_lupeon","incident_manager", "mrp_bom_cost", "web",
                "sale_stock_info_popup", "purchase_custom_lupeon"],
    "qweb": [
        "static/src/xml/qty_popip_fix.xml",
        "static/src/xml/custom_info_widget.xml",
    ],
    "data": [
        'data/sequence.xml',
        'security/groups.xml',
        'wizard/question_cancel.xml',
        'views/partner_view.xml',
        'views/sale_view.xml',
        'views/invoice_view.xml',
        'views/stock_view.xml',
        'views/mrp_production_view.xml',
        # 'views/mrp_workorder_view.xml',
        'views/assets.xml',
        'views/payment_mode_view.xml',
        'views/report_facturae.xml',
        'views/account_menus.xml',
        'views/purchase_view.xml',
        'views/product_view.xml',
        'views/crm_lead.xml'],
}
